version: "3.1"
services:
  mysql-wordpress:
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    ports:
      - 8081:3306
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks: 
      - web-networks

  wordpress:
    image: wordpress:${WP_VERSION}
    restart: always
    depends_on:
      - mysql-wordpress
    volumes:
      - ./src/themes/:/var/www/html/wp-content/themes
      - ./src/plugins/:/var/www/html/wp-content/plugins
      - ./src/uploads/:/var/www/html/wp-content/uploads
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - 80:80
    env_file:
      - ./.env
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    hostname: ${HOST}
    networks: 
      - web-networks


  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on: 
      - mysql-wordpress
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      - PMA_HOST=${MYSQL_HOST}
      - PMA_PMADB=${MYSQL_DATABASE}
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_CONTROLUSER=${DB_USER}
      - PMA_CONTROLPASS=${MYSQL_ROOT_PASSWORD}
      - UPLOAD_LIMIT=1G
    ports:
      - 9000:80
    networks: 
      - web-networks
      
  gulp:
    depends_on: 
      - wordpress
    image: gulp
    build:
      context: ./src
      dockerfile: ../Dockerfile
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./src/themes/:/var/www/html/themes
      - ./gulp/gulp-tasks:/var/www/html/gulp/gulp-tasks
      - ./gulpfile.js:/var/www/html/gulpfile.js
    command: "npm run watch"
    networks: 
      - web-networks

networks: 
  web-networks:
    name: web-networks